// Code generated by MockGen. DO NOT EDIT.
// Source: bitmoi/backend/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	db "bitmoi/backend/db/sqlc"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CheckAttendTx mocks base method.
func (m *MockStore) CheckAttendTx(arg0 context.Context, arg1 db.CheckAttendTxParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAttendTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAttendTx indicates an expected call of CheckAttendTx.
func (mr *MockStoreMockRecorder) CheckAttendTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAttendTx", reflect.TypeOf((*MockStore)(nil).CheckAttendTx), arg0, arg1)
}

// CreateBiddingHistory mocks base method.
func (m *MockStore) CreateBiddingHistory(arg0 context.Context, arg1 db.CreateBiddingHistoryParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBiddingHistory", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBiddingHistory indicates an expected call of CreateBiddingHistory.
func (mr *MockStoreMockRecorder) CreateBiddingHistory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBiddingHistory", reflect.TypeOf((*MockStore)(nil).CreateBiddingHistory), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// CreateUsedToken mocks base method.
func (m *MockStore) CreateUsedToken(arg0 context.Context, arg1 db.CreateUsedTokenParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUsedToken", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUsedToken indicates an expected call of CreateUsedToken.
func (mr *MockStoreMockRecorder) CreateUsedToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUsedToken", reflect.TypeOf((*MockStore)(nil).CreateUsedToken), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserTx mocks base method.
func (m *MockStore) CreateUserTx(arg0 context.Context, arg1 db.CreateUserTxParams) (db.CreateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockStoreMockRecorder) CreateUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockStore)(nil).CreateUserTx), arg0, arg1)
}

// CreateVerifyEmail mocks base method.
func (m *MockStore) CreateVerifyEmail(arg0 context.Context, arg1 db.CreateVerifyEmailParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerifyEmail indicates an expected call of CreateVerifyEmail.
func (mr *MockStoreMockRecorder) CreateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyEmail", reflect.TypeOf((*MockStore)(nil).CreateVerifyEmail), arg0, arg1)
}

// Get15mCandles mocks base method.
func (m *MockStore) Get15mCandles(arg0 context.Context, arg1 db.Get15mCandlesParams) ([]db.Candles15m, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get15mCandles", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles15m)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get15mCandles indicates an expected call of Get15mCandles.
func (mr *MockStoreMockRecorder) Get15mCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get15mCandles", reflect.TypeOf((*MockStore)(nil).Get15mCandles), arg0, arg1)
}

// Get15mCandlesRnage mocks base method.
func (m *MockStore) Get15mCandlesRnage(arg0 context.Context, arg1 db.Get15mCandlesRnageParams) ([]db.Candles15m, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get15mCandlesRnage", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles15m)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get15mCandlesRnage indicates an expected call of Get15mCandlesRnage.
func (mr *MockStoreMockRecorder) Get15mCandlesRnage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get15mCandlesRnage", reflect.TypeOf((*MockStore)(nil).Get15mCandlesRnage), arg0, arg1)
}

// Get15mMinMaxTime mocks base method.
func (m *MockStore) Get15mMinMaxTime(arg0 context.Context, arg1 string) (db.Get15mMinMaxTimeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get15mMinMaxTime", arg0, arg1)
	ret0, _ := ret[0].(db.Get15mMinMaxTimeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get15mMinMaxTime indicates an expected call of Get15mMinMaxTime.
func (mr *MockStoreMockRecorder) Get15mMinMaxTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get15mMinMaxTime", reflect.TypeOf((*MockStore)(nil).Get15mMinMaxTime), arg0, arg1)
}

// Get15mResult mocks base method.
func (m *MockStore) Get15mResult(arg0 context.Context, arg1 db.Get15mResultParams) ([]db.Candles15m, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get15mResult", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles15m)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get15mResult indicates an expected call of Get15mResult.
func (mr *MockStoreMockRecorder) Get15mResult(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get15mResult", reflect.TypeOf((*MockStore)(nil).Get15mResult), arg0, arg1)
}

// Get15mVolSumPriceAVG mocks base method.
func (m *MockStore) Get15mVolSumPriceAVG(arg0 context.Context, arg1 db.Get15mVolSumPriceAVGParams) (db.Get15mVolSumPriceAVGRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get15mVolSumPriceAVG", arg0, arg1)
	ret0, _ := ret[0].(db.Get15mVolSumPriceAVGRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get15mVolSumPriceAVG indicates an expected call of Get15mVolSumPriceAVG.
func (mr *MockStoreMockRecorder) Get15mVolSumPriceAVG(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get15mVolSumPriceAVG", reflect.TypeOf((*MockStore)(nil).Get15mVolSumPriceAVG), arg0, arg1)
}

// Get1dCandles mocks base method.
func (m *MockStore) Get1dCandles(arg0 context.Context, arg1 db.Get1dCandlesParams) ([]db.Candles1d, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1dCandles", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles1d)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1dCandles indicates an expected call of Get1dCandles.
func (mr *MockStoreMockRecorder) Get1dCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1dCandles", reflect.TypeOf((*MockStore)(nil).Get1dCandles), arg0, arg1)
}

// Get1dCandlesRnage mocks base method.
func (m *MockStore) Get1dCandlesRnage(arg0 context.Context, arg1 db.Get1dCandlesRnageParams) ([]db.Candles1d, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1dCandlesRnage", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles1d)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1dCandlesRnage indicates an expected call of Get1dCandlesRnage.
func (mr *MockStoreMockRecorder) Get1dCandlesRnage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1dCandlesRnage", reflect.TypeOf((*MockStore)(nil).Get1dCandlesRnage), arg0, arg1)
}

// Get1dMinMaxTime mocks base method.
func (m *MockStore) Get1dMinMaxTime(arg0 context.Context, arg1 string) (db.Get1dMinMaxTimeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1dMinMaxTime", arg0, arg1)
	ret0, _ := ret[0].(db.Get1dMinMaxTimeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1dMinMaxTime indicates an expected call of Get1dMinMaxTime.
func (mr *MockStoreMockRecorder) Get1dMinMaxTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1dMinMaxTime", reflect.TypeOf((*MockStore)(nil).Get1dMinMaxTime), arg0, arg1)
}

// Get1dResult mocks base method.
func (m *MockStore) Get1dResult(arg0 context.Context, arg1 db.Get1dResultParams) ([]db.Candles1d, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1dResult", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles1d)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1dResult indicates an expected call of Get1dResult.
func (mr *MockStoreMockRecorder) Get1dResult(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1dResult", reflect.TypeOf((*MockStore)(nil).Get1dResult), arg0, arg1)
}

// Get1dVolSumPriceAVG mocks base method.
func (m *MockStore) Get1dVolSumPriceAVG(arg0 context.Context, arg1 db.Get1dVolSumPriceAVGParams) (db.Get1dVolSumPriceAVGRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1dVolSumPriceAVG", arg0, arg1)
	ret0, _ := ret[0].(db.Get1dVolSumPriceAVGRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1dVolSumPriceAVG indicates an expected call of Get1dVolSumPriceAVG.
func (mr *MockStoreMockRecorder) Get1dVolSumPriceAVG(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1dVolSumPriceAVG", reflect.TypeOf((*MockStore)(nil).Get1dVolSumPriceAVG), arg0, arg1)
}

// Get1hCandles mocks base method.
func (m *MockStore) Get1hCandles(arg0 context.Context, arg1 db.Get1hCandlesParams) ([]db.Candles1h, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1hCandles", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles1h)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1hCandles indicates an expected call of Get1hCandles.
func (mr *MockStoreMockRecorder) Get1hCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1hCandles", reflect.TypeOf((*MockStore)(nil).Get1hCandles), arg0, arg1)
}

// Get1hCandlesRnage mocks base method.
func (m *MockStore) Get1hCandlesRnage(arg0 context.Context, arg1 db.Get1hCandlesRnageParams) ([]db.Candles1h, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1hCandlesRnage", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles1h)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1hCandlesRnage indicates an expected call of Get1hCandlesRnage.
func (mr *MockStoreMockRecorder) Get1hCandlesRnage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1hCandlesRnage", reflect.TypeOf((*MockStore)(nil).Get1hCandlesRnage), arg0, arg1)
}

// Get1hEntryTimestamp mocks base method.
func (m *MockStore) Get1hEntryTimestamp(arg0 context.Context, arg1 db.Get1hEntryTimestampParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1hEntryTimestamp", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1hEntryTimestamp indicates an expected call of Get1hEntryTimestamp.
func (mr *MockStoreMockRecorder) Get1hEntryTimestamp(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1hEntryTimestamp", reflect.TypeOf((*MockStore)(nil).Get1hEntryTimestamp), arg0, arg1)
}

// Get1hMinMaxTime mocks base method.
func (m *MockStore) Get1hMinMaxTime(arg0 context.Context, arg1 string) (db.Get1hMinMaxTimeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1hMinMaxTime", arg0, arg1)
	ret0, _ := ret[0].(db.Get1hMinMaxTimeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1hMinMaxTime indicates an expected call of Get1hMinMaxTime.
func (mr *MockStoreMockRecorder) Get1hMinMaxTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1hMinMaxTime", reflect.TypeOf((*MockStore)(nil).Get1hMinMaxTime), arg0, arg1)
}

// Get1hResult mocks base method.
func (m *MockStore) Get1hResult(arg0 context.Context, arg1 db.Get1hResultParams) ([]db.Candles1h, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1hResult", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles1h)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1hResult indicates an expected call of Get1hResult.
func (mr *MockStoreMockRecorder) Get1hResult(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1hResult", reflect.TypeOf((*MockStore)(nil).Get1hResult), arg0, arg1)
}

// Get1hVolSumPriceAVG mocks base method.
func (m *MockStore) Get1hVolSumPriceAVG(arg0 context.Context, arg1 db.Get1hVolSumPriceAVGParams) (db.Get1hVolSumPriceAVGRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get1hVolSumPriceAVG", arg0, arg1)
	ret0, _ := ret[0].(db.Get1hVolSumPriceAVGRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get1hVolSumPriceAVG indicates an expected call of Get1hVolSumPriceAVG.
func (mr *MockStoreMockRecorder) Get1hVolSumPriceAVG(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get1hVolSumPriceAVG", reflect.TypeOf((*MockStore)(nil).Get1hVolSumPriceAVG), arg0, arg1)
}

// Get4hCandles mocks base method.
func (m *MockStore) Get4hCandles(arg0 context.Context, arg1 db.Get4hCandlesParams) ([]db.Candles4h, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get4hCandles", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles4h)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get4hCandles indicates an expected call of Get4hCandles.
func (mr *MockStoreMockRecorder) Get4hCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get4hCandles", reflect.TypeOf((*MockStore)(nil).Get4hCandles), arg0, arg1)
}

// Get4hCandlesRnage mocks base method.
func (m *MockStore) Get4hCandlesRnage(arg0 context.Context, arg1 db.Get4hCandlesRnageParams) ([]db.Candles4h, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get4hCandlesRnage", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles4h)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get4hCandlesRnage indicates an expected call of Get4hCandlesRnage.
func (mr *MockStoreMockRecorder) Get4hCandlesRnage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get4hCandlesRnage", reflect.TypeOf((*MockStore)(nil).Get4hCandlesRnage), arg0, arg1)
}

// Get4hMinMaxTime mocks base method.
func (m *MockStore) Get4hMinMaxTime(arg0 context.Context, arg1 string) (db.Get4hMinMaxTimeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get4hMinMaxTime", arg0, arg1)
	ret0, _ := ret[0].(db.Get4hMinMaxTimeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get4hMinMaxTime indicates an expected call of Get4hMinMaxTime.
func (mr *MockStoreMockRecorder) Get4hMinMaxTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get4hMinMaxTime", reflect.TypeOf((*MockStore)(nil).Get4hMinMaxTime), arg0, arg1)
}

// Get4hResult mocks base method.
func (m *MockStore) Get4hResult(arg0 context.Context, arg1 db.Get4hResultParams) ([]db.Candles4h, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get4hResult", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles4h)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get4hResult indicates an expected call of Get4hResult.
func (mr *MockStoreMockRecorder) Get4hResult(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get4hResult", reflect.TypeOf((*MockStore)(nil).Get4hResult), arg0, arg1)
}

// Get4hVolSumPriceAVG mocks base method.
func (m *MockStore) Get4hVolSumPriceAVG(arg0 context.Context, arg1 db.Get4hVolSumPriceAVGParams) (db.Get4hVolSumPriceAVGRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get4hVolSumPriceAVG", arg0, arg1)
	ret0, _ := ret[0].(db.Get4hVolSumPriceAVGRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get4hVolSumPriceAVG indicates an expected call of Get4hVolSumPriceAVG.
func (mr *MockStoreMockRecorder) Get4hVolSumPriceAVG(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get4hVolSumPriceAVG", reflect.TypeOf((*MockStore)(nil).Get4hVolSumPriceAVG), arg0, arg1)
}

// Get5mCandles mocks base method.
func (m *MockStore) Get5mCandles(arg0 context.Context, arg1 db.Get5mCandlesParams) ([]db.Candles5m, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get5mCandles", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles5m)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get5mCandles indicates an expected call of Get5mCandles.
func (mr *MockStoreMockRecorder) Get5mCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get5mCandles", reflect.TypeOf((*MockStore)(nil).Get5mCandles), arg0, arg1)
}

// Get5mCandlesRnage mocks base method.
func (m *MockStore) Get5mCandlesRnage(arg0 context.Context, arg1 db.Get5mCandlesRnageParams) ([]db.Candles5m, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get5mCandlesRnage", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles5m)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get5mCandlesRnage indicates an expected call of Get5mCandlesRnage.
func (mr *MockStoreMockRecorder) Get5mCandlesRnage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get5mCandlesRnage", reflect.TypeOf((*MockStore)(nil).Get5mCandlesRnage), arg0, arg1)
}

// Get5mMinMaxTime mocks base method.
func (m *MockStore) Get5mMinMaxTime(arg0 context.Context, arg1 string) (db.Get5mMinMaxTimeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get5mMinMaxTime", arg0, arg1)
	ret0, _ := ret[0].(db.Get5mMinMaxTimeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get5mMinMaxTime indicates an expected call of Get5mMinMaxTime.
func (mr *MockStoreMockRecorder) Get5mMinMaxTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get5mMinMaxTime", reflect.TypeOf((*MockStore)(nil).Get5mMinMaxTime), arg0, arg1)
}

// Get5mResult mocks base method.
func (m *MockStore) Get5mResult(arg0 context.Context, arg1 db.Get5mResultParams) ([]db.Candles5m, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get5mResult", arg0, arg1)
	ret0, _ := ret[0].([]db.Candles5m)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get5mResult indicates an expected call of Get5mResult.
func (mr *MockStoreMockRecorder) Get5mResult(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get5mResult", reflect.TypeOf((*MockStore)(nil).Get5mResult), arg0, arg1)
}

// Get5mVolSumPriceAVG mocks base method.
func (m *MockStore) Get5mVolSumPriceAVG(arg0 context.Context, arg1 db.Get5mVolSumPriceAVGParams) (db.Get5mVolSumPriceAVGRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get5mVolSumPriceAVG", arg0, arg1)
	ret0, _ := ret[0].(db.Get5mVolSumPriceAVGRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get5mVolSumPriceAVG indicates an expected call of Get5mVolSumPriceAVG.
func (mr *MockStoreMockRecorder) Get5mVolSumPriceAVG(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get5mVolSumPriceAVG", reflect.TypeOf((*MockStore)(nil).Get5mVolSumPriceAVG), arg0, arg1)
}

// GetAllParisInDB mocks base method.
func (m *MockStore) GetAllParisInDB(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllParisInDB", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllParisInDB indicates an expected call of GetAllParisInDB.
func (mr *MockStoreMockRecorder) GetAllParisInDB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllParisInDB", reflect.TypeOf((*MockStore)(nil).GetAllParisInDB), arg0)
}

// GetAllRanks mocks base method.
func (m *MockStore) GetAllRanks(arg0 context.Context, arg1 db.GetAllRanksParams) ([]db.RankingBoard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRanks", arg0, arg1)
	ret0, _ := ret[0].([]db.RankingBoard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRanks indicates an expected call of GetAllRanks.
func (mr *MockStoreMockRecorder) GetAllRanks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRanks", reflect.TypeOf((*MockStore)(nil).GetAllRanks), arg0, arg1)
}

// GetCompScore mocks base method.
func (m *MockStore) GetCompScore(arg0 context.Context, arg1 db.GetCompScoreParams) (db.CompScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompScore", arg0, arg1)
	ret0, _ := ret[0].(db.CompScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompScore indicates an expected call of GetCompScore.
func (mr *MockStoreMockRecorder) GetCompScore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompScore", reflect.TypeOf((*MockStore)(nil).GetCompScore), arg0, arg1)
}

// GetCompScoreToStage mocks base method.
func (m *MockStore) GetCompScoreToStage(arg0 context.Context, arg1 db.GetCompScoreToStageParams) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompScoreToStage", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompScoreToStage indicates an expected call of GetCompScoreToStage.
func (mr *MockStoreMockRecorder) GetCompScoreToStage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompScoreToStage", reflect.TypeOf((*MockStore)(nil).GetCompScoreToStage), arg0, arg1)
}

// GetCompScoresByScoreID mocks base method.
func (m *MockStore) GetCompScoresByScoreID(arg0 context.Context, arg1 db.GetCompScoresByScoreIDParams) ([]db.CompScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompScoresByScoreID", arg0, arg1)
	ret0, _ := ret[0].([]db.CompScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompScoresByScoreID indicates an expected call of GetCompScoresByScoreID.
func (mr *MockStoreMockRecorder) GetCompScoresByScoreID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompScoresByScoreID", reflect.TypeOf((*MockStore)(nil).GetCompScoresByScoreID), arg0, arg1)
}

// GetCompScoresByStage mocks base method.
func (m *MockStore) GetCompScoresByStage(arg0 context.Context, arg1 db.GetCompScoresByStageParams) (db.CompScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompScoresByStage", arg0, arg1)
	ret0, _ := ret[0].(db.CompScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompScoresByStage indicates an expected call of GetCompScoresByStage.
func (mr *MockStoreMockRecorder) GetCompScoresByStage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompScoresByStage", reflect.TypeOf((*MockStore)(nil).GetCompScoresByStage), arg0, arg1)
}

// GetCompScoresByUserID mocks base method.
func (m *MockStore) GetCompScoresByUserID(arg0 context.Context, arg1 db.GetCompScoresByUserIDParams) ([]db.CompScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompScoresByUserID", arg0, arg1)
	ret0, _ := ret[0].([]db.CompScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompScoresByUserID indicates an expected call of GetCompScoresByUserID.
func (mr *MockStoreMockRecorder) GetCompScoresByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompScoresByUserID", reflect.TypeOf((*MockStore)(nil).GetCompScoresByUserID), arg0, arg1)
}

// GetCompStageLenByScoreID mocks base method.
func (m *MockStore) GetCompStageLenByScoreID(arg0 context.Context, arg1 db.GetCompStageLenByScoreIDParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompStageLenByScoreID", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompStageLenByScoreID indicates an expected call of GetCompStageLenByScoreID.
func (mr *MockStoreMockRecorder) GetCompStageLenByScoreID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompStageLenByScoreID", reflect.TypeOf((*MockStore)(nil).GetCompStageLenByScoreID), arg0, arg1)
}

// GetHighestBidder mocks base method.
func (m *MockStore) GetHighestBidder(arg0 context.Context, arg1 db.GetHighestBidderParams) (db.BiddingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighestBidder", arg0, arg1)
	ret0, _ := ret[0].(db.BiddingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighestBidder indicates an expected call of GetHighestBidder.
func (mr *MockStoreMockRecorder) GetHighestBidder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighestBidder", reflect.TypeOf((*MockStore)(nil).GetHighestBidder), arg0, arg1)
}

// GetHistoryByLocation mocks base method.
func (m *MockStore) GetHistoryByLocation(arg0 context.Context, arg1 db.GetHistoryByLocationParams) ([]db.BiddingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryByLocation", arg0, arg1)
	ret0, _ := ret[0].([]db.BiddingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryByLocation indicates an expected call of GetHistoryByLocation.
func (mr *MockStoreMockRecorder) GetHistoryByLocation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryByLocation", reflect.TypeOf((*MockStore)(nil).GetHistoryByLocation), arg0, arg1)
}

// GetHistoryByUser mocks base method.
func (m *MockStore) GetHistoryByUser(arg0 context.Context, arg1 string) ([]db.BiddingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryByUser", arg0, arg1)
	ret0, _ := ret[0].([]db.BiddingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryByUser indicates an expected call of GetHistoryByUser.
func (mr *MockStoreMockRecorder) GetHistoryByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryByUser", reflect.TypeOf((*MockStore)(nil).GetHistoryByUser), arg0, arg1)
}

// GetLastUserID mocks base method.
func (m *MockStore) GetLastUserID(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUserID", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUserID indicates an expected call of GetLastUserID.
func (mr *MockStoreMockRecorder) GetLastUserID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUserID", reflect.TypeOf((*MockStore)(nil).GetLastUserID), arg0)
}

// GetPracScore mocks base method.
func (m *MockStore) GetPracScore(arg0 context.Context, arg1 db.GetPracScoreParams) (db.PracScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPracScore", arg0, arg1)
	ret0, _ := ret[0].(db.PracScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPracScore indicates an expected call of GetPracScore.
func (mr *MockStoreMockRecorder) GetPracScore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPracScore", reflect.TypeOf((*MockStore)(nil).GetPracScore), arg0, arg1)
}

// GetPracScoreToStage mocks base method.
func (m *MockStore) GetPracScoreToStage(arg0 context.Context, arg1 db.GetPracScoreToStageParams) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPracScoreToStage", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPracScoreToStage indicates an expected call of GetPracScoreToStage.
func (mr *MockStoreMockRecorder) GetPracScoreToStage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPracScoreToStage", reflect.TypeOf((*MockStore)(nil).GetPracScoreToStage), arg0, arg1)
}

// GetPracScoresByStage mocks base method.
func (m *MockStore) GetPracScoresByStage(arg0 context.Context, arg1 db.GetPracScoresByStageParams) (db.PracScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPracScoresByStage", arg0, arg1)
	ret0, _ := ret[0].(db.PracScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPracScoresByStage indicates an expected call of GetPracScoresByStage.
func (mr *MockStoreMockRecorder) GetPracScoresByStage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPracScoresByStage", reflect.TypeOf((*MockStore)(nil).GetPracScoresByStage), arg0, arg1)
}

// GetPracScoresByUserID mocks base method.
func (m *MockStore) GetPracScoresByUserID(arg0 context.Context, arg1 db.GetPracScoresByUserIDParams) ([]db.PracScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPracScoresByUserID", arg0, arg1)
	ret0, _ := ret[0].([]db.PracScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPracScoresByUserID indicates an expected call of GetPracScoresByUserID.
func (mr *MockStoreMockRecorder) GetPracScoresByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPracScoresByUserID", reflect.TypeOf((*MockStore)(nil).GetPracScoresByUserID), arg0, arg1)
}

// GetPracStageLenByScoreID mocks base method.
func (m *MockStore) GetPracStageLenByScoreID(arg0 context.Context, arg1 db.GetPracStageLenByScoreIDParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPracStageLenByScoreID", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPracStageLenByScoreID indicates an expected call of GetPracStageLenByScoreID.
func (mr *MockStoreMockRecorder) GetPracStageLenByScoreID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPracStageLenByScoreID", reflect.TypeOf((*MockStore)(nil).GetPracStageLenByScoreID), arg0, arg1)
}

// GetRandomUser mocks base method.
func (m *MockStore) GetRandomUser(arg0 context.Context) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomUser", arg0)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomUser indicates an expected call of GetRandomUser.
func (mr *MockStoreMockRecorder) GetRandomUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomUser", reflect.TypeOf((*MockStore)(nil).GetRandomUser), arg0)
}

// GetRankByUserID mocks base method.
func (m *MockStore) GetRankByUserID(arg0 context.Context, arg1 string) (db.RankingBoard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRankByUserID", arg0, arg1)
	ret0, _ := ret[0].(db.RankingBoard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRankByUserID indicates an expected call of GetRankByUserID.
func (mr *MockStoreMockRecorder) GetRankByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRankByUserID", reflect.TypeOf((*MockStore)(nil).GetRankByUserID), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(arg0 context.Context, arg1 string) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), arg0, arg1)
}

// GetTopRankers mocks base method.
func (m *MockStore) GetTopRankers(arg0 context.Context, arg1 db.GetTopRankersParams) ([]db.RankingBoard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopRankers", arg0, arg1)
	ret0, _ := ret[0].([]db.RankingBoard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopRankers indicates an expected call of GetTopRankers.
func (mr *MockStoreMockRecorder) GetTopRankers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopRankers", reflect.TypeOf((*MockStore)(nil).GetTopRankers), arg0, arg1)
}

// GetUnsettledCompScores mocks base method.
func (m *MockStore) GetUnsettledCompScores(arg0 context.Context, arg1 string) ([]db.CompScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnsettledCompScores", arg0, arg1)
	ret0, _ := ret[0].([]db.CompScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnsettledCompScores indicates an expected call of GetUnsettledCompScores.
func (mr *MockStoreMockRecorder) GetUnsettledCompScores(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnsettledCompScores", reflect.TypeOf((*MockStore)(nil).GetUnsettledCompScores), arg0, arg1)
}

// GetUnsettledPracScores mocks base method.
func (m *MockStore) GetUnsettledPracScores(arg0 context.Context, arg1 string) ([]db.PracScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnsettledPracScores", arg0, arg1)
	ret0, _ := ret[0].([]db.PracScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnsettledPracScores indicates an expected call of GetUnsettledPracScores.
func (mr *MockStoreMockRecorder) GetUnsettledPracScores(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnsettledPracScores", reflect.TypeOf((*MockStore)(nil).GetUnsettledPracScores), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByMetamaskAddress mocks base method.
func (m *MockStore) GetUserByMetamaskAddress(arg0 context.Context, arg1 sql.NullString) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByMetamaskAddress", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByMetamaskAddress indicates an expected call of GetUserByMetamaskAddress.
func (mr *MockStoreMockRecorder) GetUserByMetamaskAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByMetamaskAddress", reflect.TypeOf((*MockStore)(nil).GetUserByMetamaskAddress), arg0, arg1)
}

// GetUserByNickName mocks base method.
func (m *MockStore) GetUserByNickName(arg0 context.Context, arg1 sql.NullString) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByNickName", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByNickName indicates an expected call of GetUserByNickName.
func (mr *MockStoreMockRecorder) GetUserByNickName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByNickName", reflect.TypeOf((*MockStore)(nil).GetUserByNickName), arg0, arg1)
}

// GetUserLastAccessedAt mocks base method.
func (m *MockStore) GetUserLastAccessedAt(arg0 context.Context, arg1 string) (sql.NullTime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLastAccessedAt", arg0, arg1)
	ret0, _ := ret[0].(sql.NullTime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLastAccessedAt indicates an expected call of GetUserLastAccessedAt.
func (mr *MockStoreMockRecorder) GetUserLastAccessedAt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLastAccessedAt", reflect.TypeOf((*MockStore)(nil).GetUserLastAccessedAt), arg0, arg1)
}

// GetUserPracBalance mocks base method.
func (m *MockStore) GetUserPracBalance(arg0 context.Context, arg1 string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPracBalance", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPracBalance indicates an expected call of GetUserPracBalance.
func (mr *MockStoreMockRecorder) GetUserPracBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPracBalance", reflect.TypeOf((*MockStore)(nil).GetUserPracBalance), arg0, arg1)
}

// GetUserScoreSummary mocks base method.
func (m *MockStore) GetUserScoreSummary(arg0 context.Context, arg1 sql.NullString) (db.GetUserScoreSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserScoreSummary", arg0, arg1)
	ret0, _ := ret[0].(db.GetUserScoreSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserScoreSummary indicates an expected call of GetUserScoreSummary.
func (mr *MockStoreMockRecorder) GetUserScoreSummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserScoreSummary", reflect.TypeOf((*MockStore)(nil).GetUserScoreSummary), arg0, arg1)
}

// GetVerifyEmails mocks base method.
func (m *MockStore) GetVerifyEmails(arg0 context.Context, arg1 db.GetVerifyEmailsParams) (db.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerifyEmails", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerifyEmails indicates an expected call of GetVerifyEmails.
func (mr *MockStoreMockRecorder) GetVerifyEmails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerifyEmails", reflect.TypeOf((*MockStore)(nil).GetVerifyEmails), arg0, arg1)
}

// Insert15mCandles mocks base method.
func (m *MockStore) Insert15mCandles(arg0 context.Context, arg1 db.Insert15mCandlesParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert15mCandles", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert15mCandles indicates an expected call of Insert15mCandles.
func (mr *MockStoreMockRecorder) Insert15mCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert15mCandles", reflect.TypeOf((*MockStore)(nil).Insert15mCandles), arg0, arg1)
}

// Insert1dCandles mocks base method.
func (m *MockStore) Insert1dCandles(arg0 context.Context, arg1 db.Insert1dCandlesParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert1dCandles", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert1dCandles indicates an expected call of Insert1dCandles.
func (mr *MockStoreMockRecorder) Insert1dCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert1dCandles", reflect.TypeOf((*MockStore)(nil).Insert1dCandles), arg0, arg1)
}

// Insert1hCandles mocks base method.
func (m *MockStore) Insert1hCandles(arg0 context.Context, arg1 db.Insert1hCandlesParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert1hCandles", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert1hCandles indicates an expected call of Insert1hCandles.
func (mr *MockStoreMockRecorder) Insert1hCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert1hCandles", reflect.TypeOf((*MockStore)(nil).Insert1hCandles), arg0, arg1)
}

// Insert4hCandles mocks base method.
func (m *MockStore) Insert4hCandles(arg0 context.Context, arg1 db.Insert4hCandlesParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert4hCandles", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert4hCandles indicates an expected call of Insert4hCandles.
func (mr *MockStoreMockRecorder) Insert4hCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert4hCandles", reflect.TypeOf((*MockStore)(nil).Insert4hCandles), arg0, arg1)
}

// Insert5mCandles mocks base method.
func (m *MockStore) Insert5mCandles(arg0 context.Context, arg1 db.Insert5mCandlesParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert5mCandles", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert5mCandles indicates an expected call of Insert5mCandles.
func (mr *MockStoreMockRecorder) Insert5mCandles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert5mCandles", reflect.TypeOf((*MockStore)(nil).Insert5mCandles), arg0, arg1)
}

// InsertCompScore mocks base method.
func (m *MockStore) InsertCompScore(arg0 context.Context, arg1 db.InsertCompScoreParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCompScore", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCompScore indicates an expected call of InsertCompScore.
func (mr *MockStoreMockRecorder) InsertCompScore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCompScore", reflect.TypeOf((*MockStore)(nil).InsertCompScore), arg0, arg1)
}

// InsertPracScore mocks base method.
func (m *MockStore) InsertPracScore(arg0 context.Context, arg1 db.InsertPracScoreParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPracScore", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPracScore indicates an expected call of InsertPracScore.
func (mr *MockStoreMockRecorder) InsertPracScore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPracScore", reflect.TypeOf((*MockStore)(nil).InsertPracScore), arg0, arg1)
}

// InsertRank mocks base method.
func (m *MockStore) InsertRank(arg0 context.Context, arg1 db.InsertRankParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRank", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRank indicates an expected call of InsertRank.
func (mr *MockStoreMockRecorder) InsertRank(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRank", reflect.TypeOf((*MockStore)(nil).InsertRank), arg0, arg1)
}

// SelectMinMaxTime mocks base method.
func (m *MockStore) SelectMinMaxTime(arg0, arg1 string, arg2 context.Context) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectMinMaxTime", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectMinMaxTime indicates an expected call of SelectMinMaxTime.
func (mr *MockStoreMockRecorder) SelectMinMaxTime(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectMinMaxTime", reflect.TypeOf((*MockStore)(nil).SelectMinMaxTime), arg0, arg1, arg2)
}

// SettleImdPracScoreTx mocks base method.
func (m *MockStore) SettleImdPracScoreTx(arg0 context.Context, arg1 db.SettleImdScoreTxParams) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SettleImdPracScoreTx", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SettleImdPracScoreTx indicates an expected call of SettleImdPracScoreTx.
func (mr *MockStoreMockRecorder) SettleImdPracScoreTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SettleImdPracScoreTx", reflect.TypeOf((*MockStore)(nil).SettleImdPracScoreTx), arg0, arg1)
}

// SpendTokenTx mocks base method.
func (m *MockStore) SpendTokenTx(arg0 context.Context, arg1 db.SpendTokenTxParams) (db.SpendTokenTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpendTokenTx", arg0, arg1)
	ret0, _ := ret[0].(db.SpendTokenTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpendTokenTx indicates an expected call of SpendTokenTx.
func (mr *MockStoreMockRecorder) SpendTokenTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpendTokenTx", reflect.TypeOf((*MockStore)(nil).SpendTokenTx), arg0, arg1)
}

// UpdateCompScoreSettledAt mocks base method.
func (m *MockStore) UpdateCompScoreSettledAt(arg0 context.Context, arg1 db.UpdateCompScoreSettledAtParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompScoreSettledAt", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCompScoreSettledAt indicates an expected call of UpdateCompScoreSettledAt.
func (mr *MockStoreMockRecorder) UpdateCompScoreSettledAt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompScoreSettledAt", reflect.TypeOf((*MockStore)(nil).UpdateCompScoreSettledAt), arg0, arg1)
}

// UpdateCompcScore mocks base method.
func (m *MockStore) UpdateCompcScore(arg0 context.Context, arg1 db.UpdateCompcScoreParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompcScore", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCompcScore indicates an expected call of UpdateCompcScore.
func (mr *MockStoreMockRecorder) UpdateCompcScore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompcScore", reflect.TypeOf((*MockStore)(nil).UpdateCompcScore), arg0, arg1)
}

// UpdatePracScore mocks base method.
func (m *MockStore) UpdatePracScore(arg0 context.Context, arg1 db.UpdatePracScoreParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePracScore", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePracScore indicates an expected call of UpdatePracScore.
func (mr *MockStoreMockRecorder) UpdatePracScore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePracScore", reflect.TypeOf((*MockStore)(nil).UpdatePracScore), arg0, arg1)
}

// UpdatePracScoreSettledAt mocks base method.
func (m *MockStore) UpdatePracScoreSettledAt(arg0 context.Context, arg1 db.UpdatePracScoreSettledAtParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePracScoreSettledAt", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePracScoreSettledAt indicates an expected call of UpdatePracScoreSettledAt.
func (mr *MockStoreMockRecorder) UpdatePracScoreSettledAt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePracScoreSettledAt", reflect.TypeOf((*MockStore)(nil).UpdatePracScoreSettledAt), arg0, arg1)
}

// UpdateUserCompBalance mocks base method.
func (m *MockStore) UpdateUserCompBalance(arg0 context.Context, arg1 db.UpdateUserCompBalanceParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserCompBalance", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserCompBalance indicates an expected call of UpdateUserCompBalance.
func (mr *MockStoreMockRecorder) UpdateUserCompBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserCompBalance", reflect.TypeOf((*MockStore)(nil).UpdateUserCompBalance), arg0, arg1)
}

// UpdateUserLastAccessedAt mocks base method.
func (m *MockStore) UpdateUserLastAccessedAt(arg0 context.Context, arg1 db.UpdateUserLastAccessedAtParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLastAccessedAt", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserLastAccessedAt indicates an expected call of UpdateUserLastAccessedAt.
func (mr *MockStoreMockRecorder) UpdateUserLastAccessedAt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLastAccessedAt", reflect.TypeOf((*MockStore)(nil).UpdateUserLastAccessedAt), arg0, arg1)
}

// UpdateUserMetamaskAddress mocks base method.
func (m *MockStore) UpdateUserMetamaskAddress(arg0 context.Context, arg1 db.UpdateUserMetamaskAddressParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserMetamaskAddress", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserMetamaskAddress indicates an expected call of UpdateUserMetamaskAddress.
func (mr *MockStoreMockRecorder) UpdateUserMetamaskAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserMetamaskAddress", reflect.TypeOf((*MockStore)(nil).UpdateUserMetamaskAddress), arg0, arg1)
}

// UpdateUserPhotoURL mocks base method.
func (m *MockStore) UpdateUserPhotoURL(arg0 context.Context, arg1 db.UpdateUserPhotoURLParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPhotoURL", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserPhotoURL indicates an expected call of UpdateUserPhotoURL.
func (mr *MockStoreMockRecorder) UpdateUserPhotoURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPhotoURL", reflect.TypeOf((*MockStore)(nil).UpdateUserPhotoURL), arg0, arg1)
}

// UpdateUserPracBalance mocks base method.
func (m *MockStore) UpdateUserPracBalance(arg0 context.Context, arg1 db.UpdateUserPracBalanceParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPracBalance", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserPracBalance indicates an expected call of UpdateUserPracBalance.
func (mr *MockStoreMockRecorder) UpdateUserPracBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPracBalance", reflect.TypeOf((*MockStore)(nil).UpdateUserPracBalance), arg0, arg1)
}

// UpdateUserRank mocks base method.
func (m *MockStore) UpdateUserRank(arg0 context.Context, arg1 db.UpdateUserRankParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRank", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRank indicates an expected call of UpdateUserRank.
func (mr *MockStoreMockRecorder) UpdateUserRank(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRank", reflect.TypeOf((*MockStore)(nil).UpdateUserRank), arg0, arg1)
}

// UpdateVerifyEmail mocks base method.
func (m *MockStore) UpdateVerifyEmail(arg0 context.Context, arg1 db.UpdateVerifyEmailParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVerifyEmail indicates an expected call of UpdateVerifyEmail.
func (mr *MockStoreMockRecorder) UpdateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerifyEmail", reflect.TypeOf((*MockStore)(nil).UpdateVerifyEmail), arg0, arg1)
}

// VerifyEmailTx mocks base method.
func (m *MockStore) VerifyEmailTx(arg0 context.Context, arg1 db.VerifyEmailTxParams) (db.VerifyEmailTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailTx", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmailTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailTx indicates an expected call of VerifyEmailTx.
func (mr *MockStoreMockRecorder) VerifyEmailTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailTx", reflect.TypeOf((*MockStore)(nil).VerifyEmailTx), arg0, arg1)
}
