version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_INITDB_SQL=CREATE DATABASE bitmoi;
      - MYSQL_DATABASE=bitmoi

  api:
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 6000:6000
      - 7001:7001
    environment:
      - DB_SOURCE=root:123@tcp(db:3306)/bitmoi?parseTime=true
    depends_on:
      - db
    entrypoint: 
      [
        "/bitmoi/wait-for.sh",
        "db:3306",
        "-t",
        "0",
        "--",
        "/bitmoi/start_api.sh"
      ]