// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: Candles.sql

package db

import (
	"context"
	"database/sql"
)

const insertCandles = `-- name: InsertCandles :execresult
INSERT INTO candles_4h (
    name,
    open,
    close,
    high,
    low,
    time,
    volume,
    color
) VALUES (
  ?,?,?,?,?,?,?,?
)
`

type InsertCandlesParams struct {
	Name   string  `json:"name"`
	Open   float64 `json:"open"`
	Close  float64 `json:"close"`
	High   float64 `json:"high"`
	Low    float64 `json:"low"`
	Time   int64   `json:"time"`
	Volume float64 `json:"volume"`
	Color  string  `json:"color"`
}

func (q *Queries) InsertCandles(ctx context.Context, arg InsertCandlesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCandles,
		arg.Name,
		arg.Open,
		arg.Close,
		arg.High,
		arg.Low,
		arg.Time,
		arg.Volume,
		arg.Color,
	)
}
