// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	InsertCandles(ctx context.Context, arg InsertCandlesParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
