// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetCandles(ctx context.Context, arg GetCandlesParams) ([]Candles4h, error)
	GetOneCandle(ctx context.Context, arg GetOneCandleParams) (Candles4h, error)
	InsertCandles(ctx context.Context, arg InsertCandlesParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
