// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: recommend_history.sql

package db

import (
	"context"
	"database/sql"
)

const createRecommendHistory = `-- name: CreateRecommendHistory :execresult
INSERT INTO recommend_history (
    from_user,
    to_user
) VALUES (
    ?, ?
)
`

type CreateRecommendHistoryParams struct {
	FromUser string `json:"from_user"`
	ToUser   string `json:"to_user"`
}

func (q *Queries) CreateRecommendHistory(ctx context.Context, arg CreateRecommendHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRecommendHistory, arg.FromUser, arg.ToUser)
}
