// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: recommend_history.sql

package db

import (
	"context"
	"database/sql"
)

const createRecommendHistory = `-- name: CreateRecommendHistory :execresult
INSERT INTO recommend_history (
    recommender,
    new_member
) VALUES (
    ?, ?
)
`

type CreateRecommendHistoryParams struct {
	Recommender string `json:"recommender"`
	NewMember   string `json:"new_member"`
}

func (q *Queries) CreateRecommendHistory(ctx context.Context, arg CreateRecommendHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRecommendHistory, arg.Recommender, arg.NewMember)
}
