// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: token.sql

package db

import (
	"context"
	"database/sql"
)

const createUsedToken = `-- name: CreateUsedToken :execresult
INSERT INTO used_token (
    score_id,
    user_id,
    metamask_address
) VALUES (
    ?, ?, ?
)
`

type CreateUsedTokenParams struct {
	ScoreID         string `json:"score_id"`
	UserID          string `json:"user_id"`
	MetamaskAddress string `json:"metamask_address"`
}

func (q *Queries) CreateUsedToken(ctx context.Context, arg CreateUsedTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUsedToken, arg.ScoreID, arg.UserID, arg.MetamaskAddress)
}
