// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    user_id,
    oauth_uid,
    full_name,
    hashed_password,
    email,
    photo_url
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	UserID         string         `json:"user_id"`
	OauthUid       sql.NullString `json:"oauth_uid"`
	FullName       string         `json:"full_name"`
	HashedPassword string         `json:"hashed_password"`
	Email          string         `json:"email"`
	PhotoUrl       sql.NullString `json:"photo_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.UserID,
		arg.OauthUid,
		arg.FullName,
		arg.HashedPassword,
		arg.Email,
		arg.PhotoUrl,
	)
}

const getLastUser = `-- name: GetLastUser :one
SELECT user_id, oauth_uid, full_name, hashed_password, email, password_changed_at, created_at, photo_url FROM users
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getLastUser)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.OauthUid,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.PhotoUrl,
	)
	return i, err
}

const getRandomUser = `-- name: GetRandomUser :one
SELECT user_id, oauth_uid, full_name, hashed_password, email, password_changed_at, created_at, photo_url FROM users
ORDER BY RAND()
LIMIT 1
`

func (q *Queries) GetRandomUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getRandomUser)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.OauthUid,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.PhotoUrl,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, oauth_uid, full_name, hashed_password, email, password_changed_at, created_at, photo_url FROM users
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.OauthUid,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.PhotoUrl,
	)
	return i, err
}

const updatePhotoURL = `-- name: UpdatePhotoURL :execresult
UPDATE users SET photo_url = ?
WHERE user_id = ?
`

type UpdatePhotoURLParams struct {
	PhotoUrl sql.NullString `json:"photo_url"`
	UserID   string         `json:"user_id"`
}

func (q *Queries) UpdatePhotoURL(ctx context.Context, arg UpdatePhotoURLParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePhotoURL, arg.PhotoUrl, arg.UserID)
}
