// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: wmoi_transaction.sql

package db

import (
	"context"
	"database/sql"
)

const createWmoiTransaction = `-- name: CreateWmoiTransaction :execresult
INSERT INTO wmoi_transaction (
    from_user,
    to_user,
    amount,
    title
) VALUES (
    ?, ?, ?, ?
)
`

type CreateWmoiTransactionParams struct {
	FromUser string `json:"from_user"`
	ToUser   string `json:"to_user"`
	Amount   int64  `json:"amount"`
	Title    string `json:"title"`
}

func (q *Queries) CreateWmoiTransaction(ctx context.Context, arg CreateWmoiTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWmoiTransaction,
		arg.FromUser,
		arg.ToUser,
		arg.Amount,
		arg.Title,
	)
}
