name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Go project
        run: |
          go build -o bitmoi

      - name: Deploy file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIV }}
          source: bitmoi,Makefile,backend/db/migrate/*
          target: /home/ubuntu/bitmoi

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIV }}
          script: |
            sudo /home/ubuntu/bitmoi/stop.sh
            sudo /home/ubuntu/bitmoi/start.sh
